import streamlit as st

st.title('Multilayer Perceptron Model')

st.write("""
## What is an MLP model?
A Multilayer Perceptron (MLP) is a type of neural network used for regression and classification tasks that involves layers of inputs and outputs fully connected by weights. MLPs are suited for complex pattern recognition and prediction problems where input data does not have spatial or temporal relationships.
""")

st.write("""
## MLP Model Used in This Project
In this project, an MLP model was developed specifically to predict the next day's price of Solana (SOL-USD). The predictive model integrated data from several sources to enhance its forecasting accuracy.

### Data Integration for Prediction
- **Predicted Prices from LSTM Models**: The MLP model utilized predicted next day price values of various cryptocurrencies including Bitcoin (BTC-USD), Ethereum (ETH-USD), Uniswap (UNI-USD), Orca (ORCA-USD), and Raydium (RAY-USD) as inputs. These predictions were generated by separate LSTM models tailored for each cryptocurrency.
- **Daily TVL Values**: Total Value Locked (TVL) daily values for Orca and Raydium were also included as inputs to enrich the model's data set, providing a broader view of the crypto market dynamics affecting Solana’s price.

### Purpose of the Model
This MLP model aimed to combine predictive insights from multiple cryptocurrencies and market indicators to forecast Solana's price more accurately for the following day. The integration of LSTM-generated predictions and TVL data exemplifies a sophisticated approach to leveraging interdependencies between different cryptocurrencies and market behaviors.
""")

st.image('./img/MLP.png', caption='Example MLP Model', use_column_width=True)

st.caption("""
For details on the individual MLP Model performance, advance to the performance page.
""")